* Spacemacs Rocks Season 2 (day-18)

Topic: how to survive in Spacemacs

** I want a feature from other editors, How could I implement it in Emacs?
   https://emacs-china.org/t/spacemacs-sublime-ctrl-d/902

** Emacs don't behavior like the other editors I used before
   - references: https://emacs-china.org/t/emacs/905
   - Some defaults are worth learning, but some are not, You can sked from eamcs-china.org
   - Stick to the defaults will help in the long run
   - Mac is the best platform, You could easily adapt yourself to Emacs (CMD A/C/X)

** I have full time job, I can't bear the efficiency lose when editing with Emacs/Spacemacs
   - I want to setup a IDE to do the job for me.
   - Suggestions:
     1) C / C++ / Java / C# / IDE is not worth the time
     2) Javascript / HTML / CSS don't need a IDE
     3) Python  / Ruby / Go / PHP / Clojure / Erlang could have some IDE feature in Emacs.
   - In the first beginning, try to use the right tool for the right job
   - Now: I'm using XCode for C/C++/OC programming, Android Studio for Java programming. (No plugin, no keybindings change)

** Don't try to make the perfect GTD tool with org-mode
   - It's very hard for beginners, I also spent too much time to configure the workflow I'm using now
   - Learn org-mode feature step by step, don't try to become the master in the first day

** Some tips for beginners to avoid common issuss
   - My Emacs is frozen,how?
     + Because Emacs is a single thread app, sometimes you just trigger some time consuming task
     #+BEGIN_SRC emacs-lisp
       ;; run shis command in your terminal(bash or zsh
       pkill -SIGUSR2 -i emacs

       ;; in emacs execute this command, else `C-g' bas been no effectively
       toggle-debug-on-quit
     #+END_SRC
   - My Emacs is very slow
     + Use the following tow command to profile the CPU with (M-x)
     #+BEGIN_SRC emacs-lisp
       profiler-start
       profiler-report
     #+END_SRC
   - My Emacs start-up time is too long
     1) use this command to start-up emacs
        #+BEGIN_SRC emacs-lisp
          /Applications/Emacs.app/Contents/MacOS/Emacs --timed-requires --profile
        #+END_SRC
     2) when emacs start-up fully, use `SPC-b-b' to switch `*load-times*' buffer to see what package is loaded too long.

** I have lots unknown of Emacs...
1. Take it easy and don't panic, Emacs is a lifelong text editor
2. Learning Emacs one piece a time everyday
3. Visit reddit/emacs-china.org regulary for keeping update with the community
4. Keep using Emacs daily and reshaping your secret weapon gradually
